### ISSUE TITLE
Streamline Usage with `parse_params!` and `parse!`

### ISSUE THREAD

**Issue by rcdilorenzo** [rcdilorenzo/filtrex#25]
If an error happens with either of these calls, they will indicate in the `Filtrex` struct that the filter is empty:

``` elixir
%Filtrex{empty: true}
```

When this value is piped into `Filtrex.query/2`, it will by default not narrow the query but could be configurable to always return an empty set of values:

``` elixir
# default behavior:
Filters.query(YourApp.YourModel, %Filtrex{empty: true})
# => does not narrow query

# optional behavior
Filters.query(YourApp.YourModel, %Filtrex{empty: true}, allow_empty: false)
# => returns query that never matches (e.g. true == false or something similar)
```

**Comment by smpallen99** [comment]
Looks great. I like default to not narrow the query. 

BTW, I tested the following..

```
import Ecto.Query

Product |> where(false) |> Repo.all
# []
```
