### ISSUE TITLE
Feedback on readme file

### ISSUE THREAD

**Issue by smpallen99** [rcdilorenzo/filtrex#26]
I like the idea of this package. Please take the following as constructive and not negative :) 
1. The title "Parsing Filters from URL Params" is confusing, and perhaps a little uninteresting. What filter are we parsing? What do I want to parse a filter? Do you mean "Build filer from Params"? Furthermore, I'm not sure why I would even be interested in the filter, aside from the validation aspect. Perhaps thats a question that could be answered in the readme :)
2. Forgive my ignorance, but I'm unfamiliar with a "smart filter". Perhaps that should be explained.
3. In this example,
   
   ```
   query = from(s in YourApp.YourModel)
     |> Filtrex.query(filter)  # => #Ecto.Query<...
   ```
   
   why would someone do this? What would I just not do `YourApp.YourModel |> Filtrex.query(filter)`?
4. I had to read section "Parsing Filter Structures" about 5 time before I realized what the section was describing. Again, I'm hung up on the verb "Parsing". If I put on my compiler hat, then I get the verb "Parsing". But it took me a while to get there. What I think is missing is some leading description that explains:
   a. two stop process. build filter, then build query
   b. filter can be created from controller params, or from more specific JSON like descriptor (needs better working, but I hope you get the point)
5. I would have one of your examples use the Ecto macro syntax. For example
   
   ```
   query = from(m in YourApp.YourModel, where: m.rating > 90)
     |> Filtrex.query(filter)  # => #Ecto.Query<...
   ```
   
   could be written as:
   
   ```
   query = YourApp.YourModel
     |> where([m], m.rating > 90)
     |> Filtrex.query(filter)
   ```
6. I was struggling with the emphasis on validation. At first, I would not see the use case since I was thinking of a static filter page (list the model fields and edit controls for each). However, I just saw the potential for a user created filter (like a query language) and realize where validation would be a neat feature. I guess my point, is that there may be two use cases here and I missed the second completely. Or am I still missing something?

The more I review this and think about it, the more potential I see with it. I think you have a useful package here.

Hope I was not too critical. 

Steve

**Comment by rcdilorenzo** [comment]
@smpallen99: I'm still planning to get back to this. I definitely appreciate your feedback.

**Comment by smpallen99** [comment]
Sorry for the delay. I’ll try to take a look at it today.
