### ISSUE TITLE
Release date for v0.3.0?

### ISSUE THREAD

**Issue by danielberkompas** [rcdilorenzo/filtrex#29]
When do you plan to release v0.3.0 on Hex? I'm building a library that depends on Filtrex, and until v0.3.0 is out, people who use my library will have to add filtrex to their `mix.exs` using a `git` reference.

**Comment by rcdilorenzo** [comment]
As soon as #25 is finished, I'll send out the v0.3.0. That said, I'm not sure when I'll get the chance to get started on that issue.

**Comment by danielberkompas** [comment]
I submitted a PR for #25, here: #30. Hopefully that helps!

**Comment by rcdilorenzo** [comment]
I've gone ahead and merged the pull-request. I'll hopefully send up the new version (`0.3.0`) later today.

**Comment by rcdilorenzo** [comment]
I've published `v0.3.0`. Thanks again for the help!
