### ISSUE TITLE
Ambiguous column error when filtering on query with joins

### ISSUE THREAD

**Issue by ryanlntn** [rcdilorenzo/filtrex#39]
When attempting to filter a query with joins on inserted_at I get a `(Postgrex.Error) ERROR 42702 (ambiguous_column): column reference "inserted_at" is ambiguous` as the fragment doesn't specify which table it's referencing.

**Comment by rcdilorenzo** [comment]
Ah, excellent catch @ryanlntn. That definitely will need to be fixed. I'll start thinking about it and see what we can do. Feel free to take a stab at yourself if you are so inclined.
