### ISSUE TITLE
Different ecto schema field name from the parameter name

### ISSUE THREAD

**Issue by bjuretic** [rcdilorenzo/filtrex#45]
Hi,

is there a support for setting a different field name for Ecto Query's where condition, so that it does not have to match the public/exposed parameter name? Imagine an API which has one field name exposed to the outside world, but another field name used internally by Ecto.

Thanks.

**Comment by bjuretic** [comment]
Solved by using public field names in the filter definitions, and then transforming the "column" in the conditions returned by Filtrex.parse_params to proper internal names.

**Comment by rcdilorenzo** [comment]
Nice work. That's what I love about functional languages. They are flexible! 😄
