### ISSUE TITLE
join fields for filtering

### ISSUE THREAD

**Issue by goravbhootra** [rcdilorenzo/filtrex#53]
Hi,

I am using filtrex in phoenix. I am receiving following params for filtering:
```
%{"status_equals"=>1,"name_contains"=>"joe black"}
```

I have three fields in the table: status (integer), first_name (string), last_name (string). I want to be able to join first name and last name to carry out the search:
`status_equals=1 AND concatenate(first_name, last_name)_contains="joe black")`

There are more filters on the page and hence, the combination of filters coming in params would keep changing.

Thanks in advance.

**Comment by goravbhootra** [comment]
It would be great if it was possible to define sql for field name - something like following:
```
def filter_options(:admin) do
    defconfig do
        number :status, allow_decimal: false, allowed_values: 1..2
        text :id_number
        text {name: fragment("concat_ws(' ', ?, ?)", :first_name, :last_name)}
    end
end
```

**Comment by rcdilorenzo** [comment]
I understand what you're saying, but I think it might be better to writing a custom query at this point. You would still be able to use `Filtrex`for everything else but would then have an extra step condition on your query _after_ `Filtrex` has done its job. I'm primarily afraid that custom SQL will really detract from the simplicity of the library and lead to other requests that might further muddy the waters.

Here's one way this could be implemented:

```elixir
def name(query, value) do
  Ecto.Query.where(query, [m],
    fragment("concat_ws(' ', ?, ?) ILIKE ?", m.first_name, m.last_name, ^value))
end
# ...

{:ok, filter} <- Filtrex.parse_params(
  Model.filter_options(:admin),
  Map.drop(params, ~w(name_contains)))

# ...
results =
  query
  |> Filtrex.query(filter)
  |> Model.Query.name(params["name_contains"])
  |> Repo.paginate(Map.put(params, :page_size, 8)) 
```

What do you think?

**Comment by goravbhootra** [comment]
@rcdilorenzo I was able to get it working with some tweaks.

I understand your concern and focus on keeping the library simple. It would be great if the library can be made extensible while keeping the complexity out. Thanks for your support and quick responses.
