### ISSUE TITLE
make text search more flexible

### ISSUE THREAD

**Issue by goravbhootra** [rcdilorenzo/filtrex#54]
Text filter is case-sensitive and filters for complete text match only at present. It would be very useful if there is an option to make it case insensitive and do partial matches as well.

Default values can be `case_sensitive: true` and `match: exact` but we could add options like below:

```text :name, case_sensitive: false, match: partial```

**Comment by rcdilorenzo** [comment]
@goravbhootra I think this behavior is achievable based on the name of the parameter. For example, you should be able to pass `name_contains=partial%20value` and it will do a `LIKE` query to Postgres. Does this solve your case or are you thinking something additional?

My primary point is to not overcomplicate the config options. If we really need to add something, though, I am willing to consider it. 👍

**Comment by goravbhootra** [comment]
apologies for disturbing, I should have read the docs more carefully!
