### ISSUE TITLE
Updating to ecto 3.0

### ISSUE THREAD

**Issue by JohnKacz** [rcdilorenzo/filtrex#58]
I think this is a pretty low effort based on [this](http://blog.plataformatec.com.br/2018/10/a-sneak-peek-at-ecto-3-0-breaking-changes/). Mostly updating tests?

I'm getting `Failed to use "ecto" (version 3.0.4) because filtrex (versions 0.4.1 and 0.4.2) requires ~> 2.1`

**Comment by rcdilorenzo** [comment]
That's probably true. Feel free to take a look if you're interested. I haven't worked consistently in Elixir for a long time, so I don't know the up-to-date features off of the top of my head.
