### ISSUE TITLE
question: if you had considered double underscores

### ISSUE THREAD

**Issue by mfrasca** [rcdilorenzo/filtrex#63]
Hi.  I was addressed to your library from the elixir forum, where I asked [this question](https://elixirforum.com/t/parsing-custom-query-language-and-query-ecto-database/23243/11) on parsing and executing complex queries.
I have not yet started using your library, just skimmed through the docs, and I have a question regarding the syntax for filters like `field >= value`.
I come from SQLAlchemy, then very briefly moved through Django, and now I landed in the Elixir environment.
in Django they have a very nice syntax for that sort of filters, and very generic, based on double underscores `__`.

for example, a filter on an hypothetical `publisher` table, only those with books rated more than 5:  `filter=Q(book__rating__gt=5)`

written this way it's easier to split the components.

the trailing compact comparison identifiers, they come from the well known set gt lt / lte gte.  (actually, I prefer the even more compact and complete: gt lt eq / le ge ne - even if the eq is redundant.)

I'm curious about your ideas.  and if you want to comment on the elixir forum, please!

**Comment by rcdilorenzo** [comment]
@mfrasca Are you still looking at this use case? I know this thread is really old. (I apologize for not responding.)

**Comment by mfrasca** [comment]
so sorry, I'm not using elixir, I was learning it at the time.
